CXX = 'clang++'
LD  = CXX
LEX = 'flex'
YACC = 'bison'

BUILD_DIR = 'build'

LEX_OUTPATH  = "#{BUILD_DIR}/lex.yy.mm"
YACC_OUTPATH = "#{BUILD_DIR}/y.tab.mm"

LEXFLAGS = [
	'-f',
	"-o #{LEX_OUTPATH}"
#	'-d'
].join(' ')

YACCFLAGS = [
	'-t',
	'-d',
	'-v',
	"-o #{YACC_OUTPATH}",
	#'-g',
	"--defines=#{BUILD_DIR}/y.tab.h"
].join(' ')

CXXFLAGS = [
	'-DDEBUG',
	'-std=gnu++98',
	'-mmacosx-version-min=10.7',
	'-I`pwd`',
	'`llvm-config --cflags`',
	'-O0',
	'-g',
	'-std=gnu++98',
	'-ObjC++',
].join(' ')


LDFLAGS = [
	'-lstdc++',
	'`llvm-config --libs`',
	'`llvm-config --ldflags`'
].join(' ')

LIBS = ['-framework Foundation'].join(' ')

PATHMAP = "build/%n.o"

OBJC_SOURCES = FileList['*.m'].add('*.mm').add('build/*.mm')
O_FILES = OBJC_SOURCES.pathmap(PATHMAP)
LEX_SOURCE = FileList['*.l'].first
YACC_SOURCE = FileList['*.y'].first

def compile(file, flags=CXXFLAGS, cc=CXX)
	sh "#{cc} #{file[:in].join(' ')} #{flags} -c -o #{file[:out]}"
end

OBJC_SOURCES.each { |src|
	file src.pathmap(PATHMAP) => src do |f|
		compile :in => f.prerequisites, :out => f.name
	end
}

task :build_parser do |t|
	sh "#{LEX} #{LEXFLAGS} #{LEX_SOURCE}"
	sh "#{YACC} #{YACCFLAGS} #{YACC_SOURCE}"
end

file :tranquil => O_FILES do |t|
	sh "#{LD} #{LDFLAGS} #{LIBS} #{O_FILES} -o #{BUILD_DIR}/#{t.name}"
end

task :default => [:build_parser, :tranquil]

task :run => [:default] do 
	sh "#{BUILD_DIR}/tranquil"
end
