gen_bridge_metadata --format complete -f AppKit -o Mac/AppKit.bridgesupport
gen_bridge_metadata --format complete -f Foundation -o Mac/Foundation.bridgesupport
gen_bridge_metadata --format complete -f ApplicationServices -o Mac/ApplicationServices.bridgesupport
gen_bridge_metadata --format complete -f AudioToolbox -o Mac/AudioToolbox.bridgesupport
gen_bridge_metadata --format complete -f AudioUnit -o Mac/AudioUnit.bridgesupport
gen_bridge_metadata --format complete -f CoreData -o Mac/CoreData.bridgesupport
gen_bridge_metadata --format complete -f Foundation -o Mac/Foundation.bridgesupport
gen_bridge_metadata --format complete -f Carbon.framework/Versions/A/Frameworks/HIToolbox -o Mac/HIToolbox.bridgesupport
gen_bridge_metadata --format complete -f QuartzCore -o Mac/QuartzCore.bridgesupport
gen_bridge_metadata --format complete -f Security -o Mac/Security.bridgesupport
gen_bridge_metadata --format complete -f Carbon.framework/Versions/A/Frameworks/SpeechRecognition -o Mac/SpeechRecognition.bridgesupport
gen_bridge_metadata --format complete -f CoreAudio -o Mac/CoreAudio.bridgesupport
gen_bridge_metadata --format complete -f DiskArbitration -o Mac/DiskArbitration.bridgesupport
gen_bridge_metadata --format complete -f CoreServices -o Mac/CoreServices.bridgesupport
gen_bridge_metadata --format complete -f OpenGL -o Mac/OpenGL.bridgesupport
gen_bridge_metadata --format complete -f CoreText -o Mac/CoreText.bridgesupport
gen_bridge_metadata --format complete -f CoreFoundation -o Mac/CoreFoundation.bridgesupport
gen_bridge_metadata --format complete -f ImageIO -o Mac/ImageIO.bridgesupport
gen_bridge_metadata --format complete -f CFNetwork -o Mac/CFNetwork.bridgesupport
gen_bridge_metadata --format complete -f SystemConfiguration -o Mac/SystemConfiguration.bridgesupport
gen_bridge_metadata --format complete -f Accelerate -o Mac/Accelerate.bridgesupport
gen_bridge_metadata --format complete -f Accelerate.framework/Versions/A/Frameworks/vImage -o Mac/vImage.bridgesupport
gen_bridge_metadata --format complete -f Accelerate.framework/Versions/A/Frameworks/vecLib -o Mac/vecLib.bridgesupport
gen_bridge_metadata --format complete -f QuartzCore -o Mac/QuartzCore.bridgesupport
gen_bridge_metadata --format complete -f QuartzCore.framework/Versions/A/Frameworks/CoreImage -o Mac/CoreImage.bridgesupport
