# Generates block dispatch stubs up to a specified maximum number of arguments

maxArgs = ARGV[0].to_i

source = "// This file was autogenerated so don't modify it.
// (Compiled with support for up to #{maxArgs} arguments)

#ifndef TQ_STUBS_H

#ifdef __cplusplus
extern \"C\" {
#endif
"

(0..maxArgs).each do |i|
    source << "id TQDispatchBlock#{i}(id block"; (1..i).each { |j| source << ", id a#{j}" }; source << ");\n"
end

source << "
#ifdef __cplusplus
}
#endif
#endif\n"
print source
