# Generates block dispatch stubs up to a specified maximum number of arguments

maxArgs = ARGV[0].to_i

source = "// This file was autogenerated so don't modify it.
// (Compiled with support for up to #{maxArgs} arguments)

#ifndef TQ_STUBS_H
#import <Foundation/Foundation.h>

#ifdef __cplusplus
extern \"C\" {
#endif

extern id (*TQBlockDispatchers[#{maxArgs+1}])(id, ...);
"

(0..maxArgs).each do |i|
    source << "id TQDispatchBlock#{i}(id block"; (1..i).each { |j| source << ", id a#{j}" }; source << ");\n"
end

# Create a NSBlock category for calling the block as well
source << "
    @interface NSBlock : NSObject
    @end

    @interface NSBlock (TQStubs)"
(0..maxArgs).each { |i|
    source << "
    - (id)call#{ (0...i).reduce("") {|s, n| s << ":(id)a#{n} "} };"
}
source << "
    - (id)callWithArguments:(NSArray *)aArguments;
@end
#ifdef __cplusplus
}
#endif
#endif\n"
print source
