#import <TQProgram.h>
#import <TQNode.h>
#import <TQNodeArgument.h>
#import <TQNodeArgumentDef.h>
#import <TQNodeBinaryOperator.h>
#import <TQNodeBlock.h>
#import <TQNodeCall.h>
#import <TQNodeClass.h>
#import <TQNodeIdentifier.h>
#import <TQNodeMemberAccess.h>
#import <TQNodeMessage.h>
#import <TQNodeMethod.h>
#import <TQNodeNumber.h>
#import <TQNodeReturn.h>
#import <TQNodeString.h>
#import <TQNodeVariable.h>
